/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: openssl.i */

#define SWIGMODULE libssl
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


    #include <openssl/ssl.h>
    #include <openssl/bio.h>
    #include <openssl/err.h>
    #include <openssl/crypto.h>
    #include <stdint.h>



extern int GoSslVerifyCb(int preverify_ok, uintptr_t x509_ctx);
int custom_ssl_verify_cb(int preverify_ok, X509_STORE_CTX *x509_ctx){
    return GoSslVerifyCb(preverify_ok, (uintptr_t)(x509_ctx));
}


extern unsigned int GoSslPskClientCbFunc(SSL *ssl,
                                               const char *hint,
                                               char *identity,
                                               unsigned int max_identity_len,
                                               unsigned char *psk,
                                               unsigned int max_psk_len);

unsigned int custom_ssl_psk_client_cb_func(SSL *ssl,
                                               const char *hint,
                                               char *identity,
                                               unsigned int max_identity_len,
                                               unsigned char *psk,
                                               unsigned int max_psk_len){
    return GoSslPskClientCbFunc(ssl, hint, identity, max_identity_len, psk, max_psk_len);
}



char *my_ssl_get_alpn_selected(const SSL *ssl){
    char *tmp;
    int len;
    SSL_get0_alpn_selected(ssl, (const unsigned char **)&tmp, &len);
    tmp[len] = '\0';
    return tmp;
}


#include <openssl/ssl.h>
#include <openssl/bio.h>
#include <openssl/evp.h>


SSL *my_bio_get_ssl(BIO *b){
    SSL *tmp;
    BIO_get_ssl(b, &tmp);
    return tmp;
}


struct bio_pair {
    BIO *bio1;
    BIO *bio2;
};
struct bio_pair * custom_new_bio_pair(){
    struct bio_pair * p = malloc(sizeof(struct bio_pair));
    int ret = BIO_new_bio_pair(&p->bio1, 0, &p->bio2, 0);
    if (ret <= 0){
        free(p);
        return NULL;
    }
    return p;
}


  #include <openssl/x509_vfy.h>  
  #include <openssl/pem.h>
  #include <openssl/store.h>
  #include <openssl/x509.h>


#include <openssl/evp.h>
#include <openssl/engine.h>

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_libssl_cc5c18f307e68e7f(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_libssl_cc5c18f307e68e7f(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_SSL_CTX_free_libssl_cc5c18f307e68e7f(SSL_CTX *_swig_go_0) {
  SSL_CTX *arg1 = (SSL_CTX *) 0 ;
  
  arg1 = *(SSL_CTX **)&_swig_go_0; 
  
  SSL_CTX_free(arg1);
  
}


intgo _wrap_SSL_set_fd_libssl_cc5c18f307e68e7f(SSL *_swig_go_0, intgo _swig_go_1) {
  SSL *arg1 = (SSL *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)SSL_set_fd(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SSL_shutdown_libssl_cc5c18f307e68e7f(SSL *_swig_go_0) {
  SSL *arg1 = (SSL *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  
  result = (int)SSL_shutdown(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_SSL_free_libssl_cc5c18f307e68e7f(SSL *_swig_go_0) {
  SSL *arg1 = (SSL *) 0 ;
  
  arg1 = *(SSL **)&_swig_go_0; 
  
  SSL_free(arg1);
  
}


intgo _wrap_SSL_accept_libssl_cc5c18f307e68e7f(SSL *_swig_go_0) {
  SSL *arg1 = (SSL *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  
  result = (int)SSL_accept(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SSL_connect_libssl_cc5c18f307e68e7f(SSL *_swig_go_0) {
  SSL *arg1 = (SSL *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  
  result = (int)SSL_connect(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void* _wrap_custom_ssl_verify_cb_libssl_cc5c18f307e68e7f() {
  int (*result)(int,X509_STORE_CTX *) = 0 ;
  void* _swig_go_result;
  
  
  result = custom_ssl_verify_cb;
  
  *(int (**)(int,X509_STORE_CTX *))&_swig_go_result = (int (*)(int,X509_STORE_CTX *))result; 
  return _swig_go_result;
}


void _wrap_SSL_set_verify_libssl_cc5c18f307e68e7f(SSL *_swig_go_0, intgo _swig_go_1, void* _swig_go_2) {
  SSL *arg1 = (SSL *) 0 ;
  int arg2 ;
  SSL_verify_cb arg3 = (SSL_verify_cb) 0 ;
  
  arg1 = *(SSL **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = *(SSL_verify_cb *)&_swig_go_2; 
  
  SSL_set_verify(arg1,arg2,arg3);
  
}


intgo _wrap_SSL_write_libssl_cc5c18f307e68e7f(SSL *_swig_go_0, _goslice_ _swig_go_1) {
  SSL *arg1 = (SSL *) 0 ;
  void *arg2 = (void *) 0 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  {
    arg2=_swig_go_1.array;
    arg3=_swig_go_1.len;
  }
  
  result = (int)SSL_write(arg1,(void const *)arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SSL_do_handshake_libssl_cc5c18f307e68e7f(SSL *_swig_go_0) {
  SSL *arg1 = (SSL *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  
  result = (int)SSL_do_handshake(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SSL_read_libssl_cc5c18f307e68e7f(SSL *_swig_go_0, _goslice_ _swig_go_1) {
  SSL *arg1 = (SSL *) 0 ;
  void *arg2 = (void *) 0 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  {
    if (_swig_go_1.len <= 0 || _swig_go_1.cap <= 0){
      arg2=NULL;
    }else{
      arg2=(void *)malloc(_swig_go_1.cap);
      arg3=_swig_go_1.cap;
    }
  }
  
  result = (int)SSL_read(arg1,arg2,arg3);
  _swig_go_result = result; 
  {
    if (arg2 != NULL){
      memcpy(_swig_go_1.array, arg2, _swig_go_1.cap);
    }
  }
  {
    if(arg2 != NULL){
      free(arg2);
    }
  }
  return _swig_go_result;
}


void* _wrap_custom_ssl_psk_client_cb_func_libssl_cc5c18f307e68e7f() {
  unsigned int (*result)(SSL *,char const *,char *,unsigned int,unsigned char *,unsigned int) = 0 ;
  void* _swig_go_result;
  
  
  result = custom_ssl_psk_client_cb_func;
  
  *(unsigned int (**)(SSL *,char const *,char *,unsigned int,unsigned char *,unsigned int))&_swig_go_result = (unsigned int (*)(SSL *,char const *,char *,unsigned int,unsigned char *,unsigned int))result; 
  return _swig_go_result;
}


void _wrap_SSL_CTX_set_psk_client_callback_libssl_cc5c18f307e68e7f(SSL_CTX *_swig_go_0, void* _swig_go_1) {
  SSL_CTX *arg1 = (SSL_CTX *) 0 ;
  SSL_psk_client_cb_func arg2 = (SSL_psk_client_cb_func) 0 ;
  
  arg1 = *(SSL_CTX **)&_swig_go_0; 
  arg2 = *(SSL_psk_client_cb_func *)&_swig_go_1; 
  
  SSL_CTX_set_psk_client_callback(arg1,arg2);
  
}


void _wrap_SSL_set_psk_client_callback_libssl_cc5c18f307e68e7f(SSL *_swig_go_0, void* _swig_go_1) {
  SSL *arg1 = (SSL *) 0 ;
  SSL_psk_client_cb_func arg2 = (SSL_psk_client_cb_func) 0 ;
  
  arg1 = *(SSL **)&_swig_go_0; 
  arg2 = *(SSL_psk_client_cb_func *)&_swig_go_1; 
  
  SSL_set_psk_client_callback(arg1,arg2);
  
}


X509 *_wrap_SSL_CTX_get0_certificate_libssl_cc5c18f307e68e7f(SSL_CTX *_swig_go_0) {
  SSL_CTX *arg1 = (SSL_CTX *) 0 ;
  X509 *result = 0 ;
  X509 *_swig_go_result;
  
  arg1 = *(SSL_CTX **)&_swig_go_0; 
  
  result = (X509 *)SSL_CTX_get0_certificate((SSL_CTX const *)arg1);
  *(X509 **)&_swig_go_result = (X509 *)result; 
  return _swig_go_result;
}


EVP_PKEY *_wrap_SSL_CTX_get0_privatekey_libssl_cc5c18f307e68e7f(SSL_CTX *_swig_go_0) {
  SSL_CTX *arg1 = (SSL_CTX *) 0 ;
  EVP_PKEY *result = 0 ;
  EVP_PKEY *_swig_go_result;
  
  arg1 = *(SSL_CTX **)&_swig_go_0; 
  
  result = (EVP_PKEY *)SSL_CTX_get0_privatekey((SSL_CTX const *)arg1);
  *(EVP_PKEY **)&_swig_go_result = (EVP_PKEY *)result; 
  return _swig_go_result;
}


void _wrap_SSL_set_connect_state_libssl_cc5c18f307e68e7f(SSL *_swig_go_0) {
  SSL *arg1 = (SSL *) 0 ;
  
  arg1 = *(SSL **)&_swig_go_0; 
  
  SSL_set_connect_state(arg1);
  
}


void _wrap_SSL_set_accept_state_libssl_cc5c18f307e68e7f(SSL *_swig_go_0) {
  SSL *arg1 = (SSL *) 0 ;
  
  arg1 = *(SSL **)&_swig_go_0; 
  
  SSL_set_accept_state(arg1);
  
}


intgo _wrap_SSL_get_error_libssl_cc5c18f307e68e7f(SSL *_swig_go_0, intgo _swig_go_1) {
  SSL *arg1 = (SSL *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)SSL_get_error((SSL const *)arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


SSL *_wrap_SSL_new_libssl_cc5c18f307e68e7f(SSL_CTX *_swig_go_0) {
  SSL_CTX *arg1 = (SSL_CTX *) 0 ;
  SSL *result = 0 ;
  SSL *_swig_go_result;
  
  arg1 = *(SSL_CTX **)&_swig_go_0; 
  
  result = (SSL *)SSL_new(arg1);
  *(SSL **)&_swig_go_result = (SSL *)result; 
  return _swig_go_result;
}


void _wrap_SSL_set_bio_libssl_cc5c18f307e68e7f(SSL *_swig_go_0, BIO *_swig_go_1, BIO *_swig_go_2) {
  SSL *arg1 = (SSL *) 0 ;
  BIO *arg2 = (BIO *) 0 ;
  BIO *arg3 = (BIO *) 0 ;
  
  arg1 = *(SSL **)&_swig_go_0; 
  arg2 = *(BIO **)&_swig_go_1; 
  arg3 = *(BIO **)&_swig_go_2; 
  
  SSL_set_bio(arg1,arg2,arg3);
  
}


SSL_CTX *_wrap_SSL_CTX_new_libssl_cc5c18f307e68e7f(SSL_METHOD *_swig_go_0) {
  SSL_METHOD *arg1 = (SSL_METHOD *) 0 ;
  SSL_CTX *result = 0 ;
  SSL_CTX *_swig_go_result;
  
  arg1 = *(SSL_METHOD **)&_swig_go_0; 
  
  result = (SSL_CTX *)SSL_CTX_new((SSL_METHOD const *)arg1);
  *(SSL_CTX **)&_swig_go_result = (SSL_CTX *)result; 
  return _swig_go_result;
}


SSL_METHOD *_wrap_TLS_method_libssl_cc5c18f307e68e7f() {
  SSL_METHOD *result = 0 ;
  SSL_METHOD *_swig_go_result;
  
  
  result = (SSL_METHOD *)TLS_method();
  *(SSL_METHOD **)&_swig_go_result = (SSL_METHOD *)result; 
  return _swig_go_result;
}


SSL_METHOD *_wrap_TLS_server_method_libssl_cc5c18f307e68e7f() {
  SSL_METHOD *result = 0 ;
  SSL_METHOD *_swig_go_result;
  
  
  result = (SSL_METHOD *)TLS_server_method();
  *(SSL_METHOD **)&_swig_go_result = (SSL_METHOD *)result; 
  return _swig_go_result;
}


SSL_METHOD *_wrap_TLS_client_method_libssl_cc5c18f307e68e7f() {
  SSL_METHOD *result = 0 ;
  SSL_METHOD *_swig_go_result;
  
  
  result = (SSL_METHOD *)TLS_client_method();
  *(SSL_METHOD **)&_swig_go_result = (SSL_METHOD *)result; 
  return _swig_go_result;
}


SSL_METHOD *_wrap_DTLS_method_libssl_cc5c18f307e68e7f() {
  SSL_METHOD *result = 0 ;
  SSL_METHOD *_swig_go_result;
  
  
  result = (SSL_METHOD *)DTLS_method();
  *(SSL_METHOD **)&_swig_go_result = (SSL_METHOD *)result; 
  return _swig_go_result;
}


SSL_METHOD *_wrap_DTLS_server_method_libssl_cc5c18f307e68e7f() {
  SSL_METHOD *result = 0 ;
  SSL_METHOD *_swig_go_result;
  
  
  result = (SSL_METHOD *)DTLS_server_method();
  *(SSL_METHOD **)&_swig_go_result = (SSL_METHOD *)result; 
  return _swig_go_result;
}


SSL_METHOD *_wrap_DTLS_client_method_libssl_cc5c18f307e68e7f() {
  SSL_METHOD *result = 0 ;
  SSL_METHOD *_swig_go_result;
  
  
  result = (SSL_METHOD *)DTLS_client_method();
  *(SSL_METHOD **)&_swig_go_result = (SSL_METHOD *)result; 
  return _swig_go_result;
}


intgo _wrap_SSL_CTX_use_certificate_libssl_cc5c18f307e68e7f(SSL_CTX *_swig_go_0, X509 *_swig_go_1) {
  SSL_CTX *arg1 = (SSL_CTX *) 0 ;
  X509 *arg2 = (X509 *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL_CTX **)&_swig_go_0; 
  arg2 = *(X509 **)&_swig_go_1; 
  
  result = (int)SSL_CTX_use_certificate(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SSL_use_certificate_libssl_cc5c18f307e68e7f(SSL *_swig_go_0, X509 *_swig_go_1) {
  SSL *arg1 = (SSL *) 0 ;
  X509 *arg2 = (X509 *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  arg2 = *(X509 **)&_swig_go_1; 
  
  result = (int)SSL_use_certificate(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SSL_use_certificate_file_libssl_cc5c18f307e68e7f(SSL *_swig_go_0, _gostring_ _swig_go_1, intgo _swig_go_2) {
  SSL *arg1 = (SSL *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (int)_swig_go_2; 
  
  result = (int)SSL_use_certificate_file(arg1,(char const *)arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_SSL_CTX_use_certificate_chain_file_libssl_cc5c18f307e68e7f(SSL_CTX *_swig_go_0, _gostring_ _swig_go_1) {
  SSL_CTX *arg1 = (SSL_CTX *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL_CTX **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)SSL_CTX_use_certificate_chain_file(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_SSL_use_certificate_chain_file_libssl_cc5c18f307e68e7f(SSL *_swig_go_0, _gostring_ _swig_go_1) {
  SSL *arg1 = (SSL *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)SSL_use_certificate_chain_file(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_SSL_CTX_use_PrivateKey_libssl_cc5c18f307e68e7f(SSL_CTX *_swig_go_0, EVP_PKEY *_swig_go_1) {
  SSL_CTX *arg1 = (SSL_CTX *) 0 ;
  EVP_PKEY *arg2 = (EVP_PKEY *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL_CTX **)&_swig_go_0; 
  arg2 = *(EVP_PKEY **)&_swig_go_1; 
  
  result = (int)SSL_CTX_use_PrivateKey(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SSL_CTX_use_PrivateKey_file_libssl_cc5c18f307e68e7f(SSL_CTX *_swig_go_0, _gostring_ _swig_go_1, intgo _swig_go_2) {
  SSL_CTX *arg1 = (SSL_CTX *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL_CTX **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (int)_swig_go_2; 
  
  result = (int)SSL_CTX_use_PrivateKey_file(arg1,(char const *)arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_SSL_use_PrivateKey_libssl_cc5c18f307e68e7f(SSL *_swig_go_0, EVP_PKEY *_swig_go_1) {
  SSL *arg1 = (SSL *) 0 ;
  EVP_PKEY *arg2 = (EVP_PKEY *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  arg2 = *(EVP_PKEY **)&_swig_go_1; 
  
  result = (int)SSL_use_PrivateKey(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SSL_set_tlsext_host_name_libssl_cc5c18f307e68e7f(SSL *_swig_go_0, _gostring_ _swig_go_1) {
  SSL *arg1 = (SSL *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)SSL_set_tlsext_host_name(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_SSL_CTX_load_verify_locations_libssl_cc5c18f307e68e7f(SSL_CTX *_swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2) {
  SSL_CTX *arg1 = (SSL_CTX *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL_CTX **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  result = (int)SSL_CTX_load_verify_locations(arg1,(char const *)arg2,(char const *)arg3);
  _swig_go_result = result; 
  free(arg2); 
  free(arg3); 
  return _swig_go_result;
}


intgo _wrap_SSL_CTX_set_default_verify_paths_libssl_cc5c18f307e68e7f(SSL_CTX *_swig_go_0) {
  SSL_CTX *arg1 = (SSL_CTX *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL_CTX **)&_swig_go_0; 
  
  result = (int)SSL_CTX_set_default_verify_paths(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SSL_want_read_libssl_cc5c18f307e68e7f(SSL *_swig_go_0) {
  SSL *arg1 = (SSL *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  
  result = (int)SSL_want_read((SSL const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SSL_want_write_libssl_cc5c18f307e68e7f(SSL *_swig_go_0) {
  SSL *arg1 = (SSL *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  
  result = (int)SSL_want_write((SSL const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SSL_CTX_set_alpn_protos_libssl_cc5c18f307e68e7f(SSL_CTX *_swig_go_0, _goslice_ _swig_go_1) {
  SSL_CTX *arg1 = (SSL_CTX *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL_CTX **)&_swig_go_0; 
  {
    arg2=_swig_go_1.array;
    arg3=_swig_go_1.len;
  }
  
  result = (int)SSL_CTX_set_alpn_protos(arg1,(unsigned char const *)arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SSL_set_alpn_protos_libssl_cc5c18f307e68e7f(SSL *_swig_go_0, _goslice_ _swig_go_1) {
  SSL *arg1 = (SSL *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  {
    arg2=_swig_go_1.array;
    arg3=_swig_go_1.len;
  }
  
  result = (int)SSL_set_alpn_protos(arg1,(unsigned char const *)arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


_gostring_ _wrap_SSL_get_alpn_selected_libssl_cc5c18f307e68e7f(SSL *_swig_go_0) {
  SSL *arg1 = (SSL *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  
  result = (char *)my_ssl_get_alpn_selected((SSL const *)arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void *_wrap_SSL_CTX_get_ex_data_libssl_cc5c18f307e68e7f(SSL_CTX *_swig_go_0, intgo _swig_go_1) {
  SSL_CTX *arg1 = (SSL_CTX *) 0 ;
  int arg2 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(SSL_CTX **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (void *)SSL_CTX_get_ex_data((SSL_CTX const *)arg1,arg2);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


intgo _wrap_SSL_CTX_set_ex_data_libssl_cc5c18f307e68e7f(SSL_CTX *_swig_go_0, intgo _swig_go_1, void *_swig_go_2) {
  SSL_CTX *arg1 = (SSL_CTX *) 0 ;
  int arg2 ;
  void *arg3 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL_CTX **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = *(void **)&_swig_go_2; 
  
  result = (int)SSL_CTX_set_ex_data(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void *_wrap_SSL_get_ex_data_libssl_cc5c18f307e68e7f(SSL *_swig_go_0, intgo _swig_go_1) {
  SSL *arg1 = (SSL *) 0 ;
  int arg2 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (void *)SSL_get_ex_data((SSL const *)arg1,arg2);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


intgo _wrap_SSL_set_ex_data_libssl_cc5c18f307e68e7f(SSL *_swig_go_0, intgo _swig_go_1, void *_swig_go_2) {
  SSL *arg1 = (SSL *) 0 ;
  int arg2 ;
  void *arg3 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = *(void **)&_swig_go_2; 
  
  result = (int)SSL_set_ex_data(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_ERR_print_errors_libssl_cc5c18f307e68e7f(BIO *_swig_go_0) {
  BIO *arg1 = (BIO *) 0 ;
  
  arg1 = *(BIO **)&_swig_go_0; 
  
  ERR_print_errors(arg1);
  
}


void _wrap_SSL_CTX_set_verify_libssl_cc5c18f307e68e7f(SSL_CTX *_swig_go_0, intgo _swig_go_1, void* _swig_go_2) {
  SSL_CTX *arg1 = (SSL_CTX *) 0 ;
  int arg2 ;
  SSL_verify_cb arg3 = (SSL_verify_cb) 0 ;
  
  arg1 = *(SSL_CTX **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = *(SSL_verify_cb *)&_swig_go_2; 
  
  SSL_CTX_set_verify(arg1,arg2,arg3);
  
}


intgo _wrap_SSL_get_ex_data_X509_STORE_CTX_idx_libssl_cc5c18f307e68e7f() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)SSL_get_ex_data_X509_STORE_CTX_idx();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_SSL_CTX_set_verify_depth_libssl_cc5c18f307e68e7f(SSL_CTX *_swig_go_0, intgo _swig_go_1) {
  SSL_CTX *arg1 = (SSL_CTX *) 0 ;
  int arg2 ;
  
  arg1 = *(SSL_CTX **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  SSL_CTX_set_verify_depth(arg1,arg2);
  
}


void _wrap_SSL_set_verify_depth_libssl_cc5c18f307e68e7f(SSL *_swig_go_0, intgo _swig_go_1) {
  SSL *arg1 = (SSL *) 0 ;
  int arg2 ;
  
  arg1 = *(SSL **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  SSL_set_verify_depth(arg1,arg2);
  
}


X509 *_wrap_SSL_get_peer_certificate_libssl_cc5c18f307e68e7f(SSL *_swig_go_0) {
  SSL *arg1 = (SSL *) 0 ;
  X509 *result = 0 ;
  X509 *_swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  
  result = (X509 *)SSL_get_peer_certificate((SSL const *)arg1);
  *(X509 **)&_swig_go_result = (X509 *)result; 
  return _swig_go_result;
}


X509_STORE *_wrap_SSL_CTX_get_cert_store_libssl_cc5c18f307e68e7f(SSL_CTX *_swig_go_0) {
  SSL_CTX *arg1 = (SSL_CTX *) 0 ;
  X509_STORE *result = 0 ;
  X509_STORE *_swig_go_result;
  
  arg1 = *(SSL_CTX **)&_swig_go_0; 
  
  result = (X509_STORE *)SSL_CTX_get_cert_store((SSL_CTX const *)arg1);
  *(X509_STORE **)&_swig_go_result = (X509_STORE *)result; 
  return _swig_go_result;
}


long long _wrap_SSL_get_verify_result_libssl_cc5c18f307e68e7f(SSL *_swig_go_0) {
  SSL *arg1 = (SSL *) 0 ;
  long result;
  long long _swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  
  result = (long)SSL_get_verify_result((SSL const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


uint64_t *_wrap_SSL_CTX_set_options_libssl_cc5c18f307e68e7f(SSL_CTX *_swig_go_0, uint64_t *_swig_go_1) {
  SSL_CTX *arg1 = (SSL_CTX *) 0 ;
  uint64_t arg2 ;
  uint64_t *argp2 ;
  uint64_t result;
  uint64_t *_swig_go_result;
  
  arg1 = *(SSL_CTX **)&_swig_go_0; 
  
  argp2 = (uint64_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null uint64_t");
  }
  arg2 = (uint64_t)*argp2;
  
  
  result = SSL_CTX_set_options(arg1,arg2);
  {
    uint64_t * resultptr = (uint64_t *)malloc(sizeof(uint64_t));
    memmove(resultptr, &result, sizeof(uint64_t));
    *(uint64_t **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


uint64_t *_wrap_SSL_set_options_libssl_cc5c18f307e68e7f(SSL *_swig_go_0, uint64_t *_swig_go_1) {
  SSL *arg1 = (SSL *) 0 ;
  uint64_t arg2 ;
  uint64_t *argp2 ;
  uint64_t result;
  uint64_t *_swig_go_result;
  
  arg1 = *(SSL **)&_swig_go_0; 
  
  argp2 = (uint64_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null uint64_t");
  }
  arg2 = (uint64_t)*argp2;
  
  
  result = SSL_set_options(arg1,arg2);
  {
    uint64_t * resultptr = (uint64_t *)malloc(sizeof(uint64_t));
    memmove(resultptr, &result, sizeof(uint64_t));
    *(uint64_t **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


BIO_METHOD *_wrap_BIO_f_base64_libssl_cc5c18f307e68e7f() {
  BIO_METHOD *result = 0 ;
  BIO_METHOD *_swig_go_result;
  
  
  result = (BIO_METHOD *)BIO_f_base64();
  *(BIO_METHOD **)&_swig_go_result = (BIO_METHOD *)result; 
  return _swig_go_result;
}


BIO_METHOD *_wrap_BIO_f_buffer_libssl_cc5c18f307e68e7f() {
  BIO_METHOD *result = 0 ;
  BIO_METHOD *_swig_go_result;
  
  
  result = (BIO_METHOD *)BIO_f_buffer();
  *(BIO_METHOD **)&_swig_go_result = (BIO_METHOD *)result; 
  return _swig_go_result;
}


BIO_METHOD *_wrap_BIO_f_cipher_libssl_cc5c18f307e68e7f() {
  BIO_METHOD *result = 0 ;
  BIO_METHOD *_swig_go_result;
  
  
  result = (BIO_METHOD *)BIO_f_cipher();
  *(BIO_METHOD **)&_swig_go_result = (BIO_METHOD *)result; 
  return _swig_go_result;
}


intgo _wrap_BIO_set_cipher_libssl_cc5c18f307e68e7f(BIO *_swig_go_0, EVP_CIPHER *_swig_go_1, _goslice_ _swig_go_2, _goslice_ _swig_go_3, intgo _swig_go_4) {
  BIO *arg1 = (BIO *) 0 ;
  EVP_CIPHER *arg2 = (EVP_CIPHER *) 0 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned char *arg4 = (unsigned char *) 0 ;
  int arg5 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  arg2 = *(EVP_CIPHER **)&_swig_go_1; 
  {
    arg3=_swig_go_2.array;
  }
  {
    arg4=_swig_go_3.array;
  }
  arg5 = (int)_swig_go_4; 
  
  result = (int)BIO_set_cipher(arg1,(EVP_CIPHER const *)arg2,(unsigned char const *)arg3,(unsigned char const *)arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


BIO_METHOD *_wrap_BIO_f_md_libssl_cc5c18f307e68e7f() {
  BIO_METHOD *result = 0 ;
  BIO_METHOD *_swig_go_result;
  
  
  result = (BIO_METHOD *)BIO_f_md();
  *(BIO_METHOD **)&_swig_go_result = (BIO_METHOD *)result; 
  return _swig_go_result;
}


intgo _wrap_BIO_set_md_libssl_cc5c18f307e68e7f(BIO *_swig_go_0, EVP_MD *_swig_go_1) {
  BIO *arg1 = (BIO *) 0 ;
  EVP_MD *arg2 = (EVP_MD *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  arg2 = *(EVP_MD **)&_swig_go_1; 
  
  result = (int)BIO_set_md(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


BIO_METHOD *_wrap_BIO_f_null_libssl_cc5c18f307e68e7f() {
  BIO_METHOD *result = 0 ;
  BIO_METHOD *_swig_go_result;
  
  
  result = (BIO_METHOD *)BIO_f_null();
  *(BIO_METHOD **)&_swig_go_result = (BIO_METHOD *)result; 
  return _swig_go_result;
}


BIO_METHOD *_wrap_BIO_f_ssl_libssl_cc5c18f307e68e7f() {
  BIO_METHOD *result = 0 ;
  BIO_METHOD *_swig_go_result;
  
  
  result = (BIO_METHOD *)BIO_f_ssl();
  *(BIO_METHOD **)&_swig_go_result = (BIO_METHOD *)result; 
  return _swig_go_result;
}


SSL *_wrap_BIO_get_ssl_libssl_cc5c18f307e68e7f(BIO *_swig_go_0) {
  BIO *arg1 = (BIO *) 0 ;
  SSL *result = 0 ;
  SSL *_swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  
  result = (SSL *)my_bio_get_ssl(arg1);
  *(SSL **)&_swig_go_result = (SSL *)result; 
  return _swig_go_result;
}


BIO *_wrap_BIO_new_libssl_cc5c18f307e68e7f(BIO_METHOD *_swig_go_0) {
  BIO_METHOD *arg1 = (BIO_METHOD *) 0 ;
  BIO *result = 0 ;
  BIO *_swig_go_result;
  
  arg1 = *(BIO_METHOD **)&_swig_go_0; 
  
  result = (BIO *)BIO_new((BIO_METHOD const *)arg1);
  *(BIO **)&_swig_go_result = (BIO *)result; 
  return _swig_go_result;
}


intgo _wrap_BIO_free_libssl_cc5c18f307e68e7f(BIO *_swig_go_0) {
  BIO *arg1 = (BIO *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  
  result = (int)BIO_free(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_BIO_free_all_libssl_cc5c18f307e68e7f(BIO *_swig_go_0) {
  BIO *arg1 = (BIO *) 0 ;
  
  arg1 = *(BIO **)&_swig_go_0; 
  
  BIO_free_all(arg1);
  
}


BIO *_wrap_BIO_push_libssl_cc5c18f307e68e7f(BIO *_swig_go_0, BIO *_swig_go_1) {
  BIO *arg1 = (BIO *) 0 ;
  BIO *arg2 = (BIO *) 0 ;
  BIO *result = 0 ;
  BIO *_swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  arg2 = *(BIO **)&_swig_go_1; 
  
  result = (BIO *)BIO_push(arg1,arg2);
  *(BIO **)&_swig_go_result = (BIO *)result; 
  return _swig_go_result;
}


BIO *_wrap_BIO_new_ssl_libssl_cc5c18f307e68e7f(SSL_CTX *_swig_go_0, intgo _swig_go_1) {
  SSL_CTX *arg1 = (SSL_CTX *) 0 ;
  int arg2 ;
  BIO *result = 0 ;
  BIO *_swig_go_result;
  
  arg1 = *(SSL_CTX **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (BIO *)BIO_new_ssl(arg1,arg2);
  *(BIO **)&_swig_go_result = (BIO *)result; 
  return _swig_go_result;
}


BIO *_wrap_BIO_new_ssl_connect_libssl_cc5c18f307e68e7f(SSL_CTX *_swig_go_0) {
  SSL_CTX *arg1 = (SSL_CTX *) 0 ;
  BIO *result = 0 ;
  BIO *_swig_go_result;
  
  arg1 = *(SSL_CTX **)&_swig_go_0; 
  
  result = (BIO *)BIO_new_ssl_connect(arg1);
  *(BIO **)&_swig_go_result = (BIO *)result; 
  return _swig_go_result;
}


void _wrap_BIO_ssl_shutdown_libssl_cc5c18f307e68e7f(BIO *_swig_go_0) {
  BIO *arg1 = (BIO *) 0 ;
  
  arg1 = *(BIO **)&_swig_go_0; 
  
  BIO_ssl_shutdown(arg1);
  
}


BIO_METHOD *_wrap_BIO_s_accept_libssl_cc5c18f307e68e7f() {
  BIO_METHOD *result = 0 ;
  BIO_METHOD *_swig_go_result;
  
  
  result = (BIO_METHOD *)BIO_s_accept();
  *(BIO_METHOD **)&_swig_go_result = (BIO_METHOD *)result; 
  return _swig_go_result;
}


BIO *_wrap_BIO_new_accept_libssl_cc5c18f307e68e7f(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  BIO *result = 0 ;
  BIO *_swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (BIO *)BIO_new_accept(arg1);
  *(BIO **)&_swig_go_result = (BIO *)result; 
  free(arg1); 
  return _swig_go_result;
}


intgo _wrap_BIO_do_accept_libssl_cc5c18f307e68e7f(BIO *_swig_go_0) {
  BIO *arg1 = (BIO *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  
  result = (int)BIO_do_accept(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_BIO_do_handshake_libssl_cc5c18f307e68e7f(BIO *_swig_go_0) {
  BIO *arg1 = (BIO *) 0 ;
  long result;
  long long _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  
  result = (long)BIO_do_handshake(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_BIO_write_libssl_cc5c18f307e68e7f(BIO *_swig_go_0, _goslice_ _swig_go_1) {
  BIO *arg1 = (BIO *) 0 ;
  void *arg2 = (void *) 0 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  {
    arg2=_swig_go_1.array;
    arg3=_swig_go_1.len;
  }
  
  result = (int)BIO_write(arg1,(void const *)arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_BIO_read_libssl_cc5c18f307e68e7f(BIO *_swig_go_0, _goslice_ _swig_go_1) {
  BIO *arg1 = (BIO *) 0 ;
  void *arg2 = (void *) 0 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  {
    if (_swig_go_1.len <= 0 || _swig_go_1.cap <= 0){
      arg2=NULL;
    }else{
      arg2=(void *)malloc(_swig_go_1.cap);
      arg3=_swig_go_1.cap;
    }
  }
  
  result = (int)BIO_read(arg1,arg2,arg3);
  _swig_go_result = result; 
  {
    if (arg2 != NULL){
      memcpy(_swig_go_1.array, arg2, _swig_go_1.cap);
    }
  }
  {
    if(arg2 != NULL){
      free(arg2);
    }
  }
  return _swig_go_result;
}


BIO_METHOD *_wrap_BIO_s_bio_libssl_cc5c18f307e68e7f() {
  BIO_METHOD *result = 0 ;
  BIO_METHOD *_swig_go_result;
  
  
  result = (BIO_METHOD *)BIO_s_bio();
  *(BIO_METHOD **)&_swig_go_result = (BIO_METHOD *)result; 
  return _swig_go_result;
}


intgo _wrap_BIO_make_bio_pair_libssl_cc5c18f307e68e7f(BIO *_swig_go_0, BIO *_swig_go_1) {
  BIO *arg1 = (BIO *) 0 ;
  BIO *arg2 = (BIO *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  arg2 = *(BIO **)&_swig_go_1; 
  
  result = (int)BIO_make_bio_pair(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_bio_pair_bio1_set_libssl_cc5c18f307e68e7f(struct bio_pair *_swig_go_0, BIO *_swig_go_1) {
  struct bio_pair *arg1 = (struct bio_pair *) 0 ;
  BIO *arg2 = (BIO *) 0 ;
  
  arg1 = *(struct bio_pair **)&_swig_go_0; 
  arg2 = *(BIO **)&_swig_go_1; 
  
  if (arg1) (arg1)->bio1 = arg2;
  
}


BIO *_wrap_bio_pair_bio1_get_libssl_cc5c18f307e68e7f(struct bio_pair *_swig_go_0) {
  struct bio_pair *arg1 = (struct bio_pair *) 0 ;
  BIO *result = 0 ;
  BIO *_swig_go_result;
  
  arg1 = *(struct bio_pair **)&_swig_go_0; 
  
  result = (BIO *) ((arg1)->bio1);
  *(BIO **)&_swig_go_result = (BIO *)result; 
  return _swig_go_result;
}


void _wrap_bio_pair_bio2_set_libssl_cc5c18f307e68e7f(struct bio_pair *_swig_go_0, BIO *_swig_go_1) {
  struct bio_pair *arg1 = (struct bio_pair *) 0 ;
  BIO *arg2 = (BIO *) 0 ;
  
  arg1 = *(struct bio_pair **)&_swig_go_0; 
  arg2 = *(BIO **)&_swig_go_1; 
  
  if (arg1) (arg1)->bio2 = arg2;
  
}


BIO *_wrap_bio_pair_bio2_get_libssl_cc5c18f307e68e7f(struct bio_pair *_swig_go_0) {
  struct bio_pair *arg1 = (struct bio_pair *) 0 ;
  BIO *result = 0 ;
  BIO *_swig_go_result;
  
  arg1 = *(struct bio_pair **)&_swig_go_0; 
  
  result = (BIO *) ((arg1)->bio2);
  *(BIO **)&_swig_go_result = (BIO *)result; 
  return _swig_go_result;
}


struct bio_pair *_wrap_new_bio_pair_libssl_cc5c18f307e68e7f() {
  struct bio_pair *result = 0 ;
  struct bio_pair *_swig_go_result;
  
  
  result = (struct bio_pair *)calloc(1, sizeof(struct bio_pair));
  *(struct bio_pair **)&_swig_go_result = (struct bio_pair *)result; 
  return _swig_go_result;
}


void _wrap_delete_bio_pair_libssl_cc5c18f307e68e7f(struct bio_pair *_swig_go_0) {
  struct bio_pair *arg1 = (struct bio_pair *) 0 ;
  
  arg1 = *(struct bio_pair **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


struct bio_pair *_wrap_BIO_new_bio_pair_libssl_cc5c18f307e68e7f() {
  struct bio_pair *result = 0 ;
  struct bio_pair *_swig_go_result;
  
  
  result = (struct bio_pair *)custom_new_bio_pair();
  *(struct bio_pair **)&_swig_go_result = (struct bio_pair *)result; 
  return _swig_go_result;
}


BIO_METHOD *_wrap_BIO_s_connect_libssl_cc5c18f307e68e7f() {
  BIO_METHOD *result = 0 ;
  BIO_METHOD *_swig_go_result;
  
  
  result = (BIO_METHOD *)BIO_s_connect();
  *(BIO_METHOD **)&_swig_go_result = (BIO_METHOD *)result; 
  return _swig_go_result;
}


BIO *_wrap_BIO_new_connect_libssl_cc5c18f307e68e7f(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  BIO *result = 0 ;
  BIO *_swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (BIO *)BIO_new_connect((char const *)arg1);
  *(BIO **)&_swig_go_result = (BIO *)result; 
  free(arg1); 
  return _swig_go_result;
}


long long _wrap_BIO_set_conn_hostname_libssl_cc5c18f307e68e7f(BIO *_swig_go_0, _gostring_ _swig_go_1) {
  BIO *arg1 = (BIO *) 0 ;
  char *arg2 = (char *) 0 ;
  long result;
  long long _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (long)BIO_set_conn_hostname(arg1,arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


long long _wrap_BIO_set_nbio_libssl_cc5c18f307e68e7f(BIO *_swig_go_0, long long _swig_go_1) {
  BIO *arg1 = (BIO *) 0 ;
  long arg2 ;
  long result;
  long long _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  arg2 = (long)_swig_go_1; 
  
  result = (long)BIO_set_nbio(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_BIO_do_connect_libssl_cc5c18f307e68e7f(BIO *_swig_go_0) {
  BIO *arg1 = (BIO *) 0 ;
  long result;
  long long _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  
  result = (long)BIO_do_connect(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


BIO_METHOD *_wrap_BIO_s_fd_libssl_cc5c18f307e68e7f() {
  BIO_METHOD *result = 0 ;
  BIO_METHOD *_swig_go_result;
  
  
  result = (BIO_METHOD *)BIO_s_fd();
  *(BIO_METHOD **)&_swig_go_result = (BIO_METHOD *)result; 
  return _swig_go_result;
}


intgo _wrap_BIO_set_fd_libssl_cc5c18f307e68e7f(BIO *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2) {
  BIO *arg1 = (BIO *) 0 ;
  int arg2 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  result = (int)BIO_set_fd(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


BIO *_wrap_BIO_new_fd_libssl_cc5c18f307e68e7f(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  BIO *result = 0 ;
  BIO *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (BIO *)BIO_new_fd(arg1,arg2);
  *(BIO **)&_swig_go_result = (BIO *)result; 
  return _swig_go_result;
}


BIO *_wrap_BIO_new_file_libssl_cc5c18f307e68e7f(_gostring_ _swig_go_0, _gostring_ _swig_go_1) {
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  BIO *result = 0 ;
  BIO *_swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (BIO *)BIO_new_file((char const *)arg1,(char const *)arg2);
  *(BIO **)&_swig_go_result = (BIO *)result; 
  free(arg1); 
  free(arg2); 
  return _swig_go_result;
}


BIO_METHOD *_wrap_BIO_s_mem_libssl_cc5c18f307e68e7f() {
  BIO_METHOD *result = 0 ;
  BIO_METHOD *_swig_go_result;
  
  
  result = (BIO_METHOD *)BIO_s_mem();
  *(BIO_METHOD **)&_swig_go_result = (BIO_METHOD *)result; 
  return _swig_go_result;
}


BIO_METHOD *_wrap_BIO_s_null_libssl_cc5c18f307e68e7f() {
  BIO_METHOD *result = 0 ;
  BIO_METHOD *_swig_go_result;
  
  
  result = (BIO_METHOD *)BIO_s_null();
  *(BIO_METHOD **)&_swig_go_result = (BIO_METHOD *)result; 
  return _swig_go_result;
}


BIO_METHOD *_wrap_BIO_s_socket_libssl_cc5c18f307e68e7f() {
  BIO_METHOD *result = 0 ;
  BIO_METHOD *_swig_go_result;
  
  
  result = (BIO_METHOD *)BIO_s_socket();
  *(BIO_METHOD **)&_swig_go_result = (BIO_METHOD *)result; 
  return _swig_go_result;
}


BIO *_wrap_BIO_new_socket_libssl_cc5c18f307e68e7f(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  BIO *result = 0 ;
  BIO *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (BIO *)BIO_new_socket(arg1,arg2);
  *(BIO **)&_swig_go_result = (BIO *)result; 
  return _swig_go_result;
}


intgo _wrap_BIO_should_read_libssl_cc5c18f307e68e7f(BIO *_swig_go_0) {
  BIO *arg1 = (BIO *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  
  result = (int)BIO_should_read(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_BIO_should_write_libssl_cc5c18f307e68e7f(BIO *_swig_go_0) {
  BIO *arg1 = (BIO *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  
  result = (int)BIO_should_write(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_BIO_should_retry_libssl_cc5c18f307e68e7f(BIO *_swig_go_0) {
  BIO *arg1 = (BIO *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  
  result = (int)BIO_should_retry(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_BIO_reset_libssl_cc5c18f307e68e7f(BIO *_swig_go_0) {
  BIO *arg1 = (BIO *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  
  result = (int)BIO_reset(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_BIO_seek_libssl_cc5c18f307e68e7f(BIO *_swig_go_0, intgo _swig_go_1) {
  BIO *arg1 = (BIO *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)BIO_seek(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_BIO_tell_libssl_cc5c18f307e68e7f(BIO *_swig_go_0) {
  BIO *arg1 = (BIO *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  
  result = (int)BIO_tell(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_BIO_flush_libssl_cc5c18f307e68e7f(BIO *_swig_go_0) {
  BIO *arg1 = (BIO *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  
  result = (int)BIO_flush(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_BIO_eof_libssl_cc5c18f307e68e7f(BIO *_swig_go_0) {
  BIO *arg1 = (BIO *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  
  result = (int)BIO_eof(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_BIO_set_close_libssl_cc5c18f307e68e7f(BIO *_swig_go_0, long long _swig_go_1) {
  BIO *arg1 = (BIO *) 0 ;
  long arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  arg2 = (long)_swig_go_1; 
  
  result = (int)BIO_set_close(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_BIO_pending_libssl_cc5c18f307e68e7f(BIO *_swig_go_0) {
  BIO *arg1 = (BIO *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  
  result = (int)BIO_pending(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_BIO_ctrl_pending_libssl_cc5c18f307e68e7f(BIO *_swig_go_0) {
  BIO *arg1 = (BIO *) 0 ;
  size_t result;
  long long _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  
  result = BIO_ctrl_pending(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_BIO_ctrl_wpending_libssl_cc5c18f307e68e7f(BIO *_swig_go_0) {
  BIO *arg1 = (BIO *) 0 ;
  size_t result;
  long long _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  
  result = BIO_ctrl_wpending(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void *_wrap_BIO_get_ex_data_libssl_cc5c18f307e68e7f(BIO *_swig_go_0, intgo _swig_go_1) {
  BIO *arg1 = (BIO *) 0 ;
  int arg2 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (void *)BIO_get_ex_data(arg1,arg2);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


intgo _wrap_BIO_set_ex_data_libssl_cc5c18f307e68e7f(BIO *_swig_go_0, intgo _swig_go_1, void *_swig_go_2) {
  BIO *arg1 = (BIO *) 0 ;
  int arg2 ;
  void *arg3 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = *(void **)&_swig_go_2; 
  
  result = (int)BIO_set_ex_data(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_BIO_gets_libssl_cc5c18f307e68e7f(BIO *_swig_go_0, _goslice_ _swig_go_1) {
  BIO *arg1 = (BIO *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  {
    if (_swig_go_1.len <= 0 || _swig_go_1.cap <= 0){
      arg2=NULL;
    }else{
      arg2=(char *)malloc(_swig_go_1.cap);
      arg3=_swig_go_1.cap;
    }
  }
  
  result = (int)BIO_gets(arg1,arg2,arg3);
  _swig_go_result = result; 
  {
    if (arg2 != NULL){
      memcpy(_swig_go_1.array, arg2, _swig_go_1.cap);
    }
  }
  {
    if(arg2 != NULL){
      free(arg2);
    }
  }
  return _swig_go_result;
}


intgo _wrap_BIO_puts_libssl_cc5c18f307e68e7f(BIO *_swig_go_0, _gostring_ _swig_go_1) {
  BIO *arg1 = (BIO *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)BIO_puts(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


EVP_PKEY *_wrap_PEM_read_bio_PrivateKey_libssl_cc5c18f307e68e7f(BIO *_swig_go_0, EVP_PKEY **_swig_go_1, void* _swig_go_2, void *_swig_go_3) {
  BIO *arg1 = (BIO *) 0 ;
  EVP_PKEY **arg2 = (EVP_PKEY **) 0 ;
  pem_password_cb *arg3 = (pem_password_cb *) 0 ;
  void *arg4 = (void *) 0 ;
  EVP_PKEY *result = 0 ;
  EVP_PKEY *_swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  arg2 = *(EVP_PKEY ***)&_swig_go_1; 
  arg3 = *(pem_password_cb **)&_swig_go_2; 
  arg4 = *(void **)&_swig_go_3; 
  
  result = (EVP_PKEY *)PEM_read_bio_PrivateKey(arg1,arg2,arg3,arg4);
  *(EVP_PKEY **)&_swig_go_result = (EVP_PKEY *)result; 
  return _swig_go_result;
}


X509 *_wrap_PEM_read_bio_X509_libssl_cc5c18f307e68e7f(BIO *_swig_go_0, X509 **_swig_go_1, void* _swig_go_2, void *_swig_go_3) {
  BIO *arg1 = (BIO *) 0 ;
  X509 **arg2 = (X509 **) 0 ;
  pem_password_cb *arg3 = (pem_password_cb *) 0 ;
  void *arg4 = (void *) 0 ;
  X509 *result = 0 ;
  X509 *_swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  arg2 = *(X509 ***)&_swig_go_1; 
  arg3 = *(pem_password_cb **)&_swig_go_2; 
  arg4 = *(void **)&_swig_go_3; 
  
  result = (X509 *)PEM_read_bio_X509(arg1,arg2,arg3,arg4);
  *(X509 **)&_swig_go_result = (X509 *)result; 
  return _swig_go_result;
}


intgo _wrap_X509_STORE_add_cert_libssl_cc5c18f307e68e7f(X509_STORE *_swig_go_0, X509 *_swig_go_1) {
  X509_STORE *arg1 = (X509_STORE *) 0 ;
  X509 *arg2 = (X509 *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(X509_STORE **)&_swig_go_0; 
  arg2 = *(X509 **)&_swig_go_1; 
  
  result = (int)X509_STORE_add_cert(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SSL_get_ex_new_index_libssl_cc5c18f307e68e7f(long long _swig_go_0, void *_swig_go_1, CRYPTO_EX_new *_swig_go_2, CRYPTO_EX_dup *_swig_go_3, CRYPTO_EX_free *_swig_go_4) {
  long arg1 ;
  void *arg2 = (void *) 0 ;
  CRYPTO_EX_new *arg3 = (CRYPTO_EX_new *) 0 ;
  CRYPTO_EX_dup *arg4 = (CRYPTO_EX_dup *) 0 ;
  CRYPTO_EX_free *arg5 = (CRYPTO_EX_free *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (long)_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  arg3 = *(CRYPTO_EX_new **)&_swig_go_2; 
  arg4 = *(CRYPTO_EX_dup **)&_swig_go_3; 
  arg5 = *(CRYPTO_EX_free **)&_swig_go_4; 
  
  result = (int)SSL_get_ex_new_index(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SSL_CTX_get_ex_new_index_libssl_cc5c18f307e68e7f(long long _swig_go_0, void *_swig_go_1, CRYPTO_EX_new *_swig_go_2, CRYPTO_EX_dup *_swig_go_3, CRYPTO_EX_free *_swig_go_4) {
  long arg1 ;
  void *arg2 = (void *) 0 ;
  CRYPTO_EX_new *arg3 = (CRYPTO_EX_new *) 0 ;
  CRYPTO_EX_dup *arg4 = (CRYPTO_EX_dup *) 0 ;
  CRYPTO_EX_free *arg5 = (CRYPTO_EX_free *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (long)_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  arg3 = *(CRYPTO_EX_new **)&_swig_go_2; 
  arg4 = *(CRYPTO_EX_dup **)&_swig_go_3; 
  arg5 = *(CRYPTO_EX_free **)&_swig_go_4; 
  
  result = (int)SSL_CTX_get_ex_new_index(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_BIO_get_ex_new_index_libssl_cc5c18f307e68e7f(long long _swig_go_0, void *_swig_go_1, CRYPTO_EX_new *_swig_go_2, CRYPTO_EX_dup *_swig_go_3, CRYPTO_EX_free *_swig_go_4) {
  long arg1 ;
  void *arg2 = (void *) 0 ;
  CRYPTO_EX_new *arg3 = (CRYPTO_EX_new *) 0 ;
  CRYPTO_EX_dup *arg4 = (CRYPTO_EX_dup *) 0 ;
  CRYPTO_EX_free *arg5 = (CRYPTO_EX_free *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (long)_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  arg3 = *(CRYPTO_EX_new **)&_swig_go_2; 
  arg4 = *(CRYPTO_EX_dup **)&_swig_go_3; 
  arg5 = *(CRYPTO_EX_free **)&_swig_go_4; 
  
  result = (int)BIO_get_ex_new_index(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


void *_wrap_X509_STORE_CTX_get_ex_data_libssl_cc5c18f307e68e7f(X509_STORE_CTX *_swig_go_0, intgo _swig_go_1) {
  X509_STORE_CTX *arg1 = (X509_STORE_CTX *) 0 ;
  int arg2 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(X509_STORE_CTX **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (void *)X509_STORE_CTX_get_ex_data(arg1,arg2);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


intgo _wrap_X509_NAME_print_libssl_cc5c18f307e68e7f(BIO *_swig_go_0, X509_NAME *_swig_go_1, intgo _swig_go_2) {
  BIO *arg1 = (BIO *) 0 ;
  X509_NAME *arg2 = (X509_NAME *) 0 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(BIO **)&_swig_go_0; 
  arg2 = *(X509_NAME **)&_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  result = (int)X509_NAME_print(arg1,(X509_NAME const *)arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


X509_NAME *_wrap_X509_get_subject_name_libssl_cc5c18f307e68e7f(X509 *_swig_go_0) {
  X509 *arg1 = (X509 *) 0 ;
  X509_NAME *result = 0 ;
  X509_NAME *_swig_go_result;
  
  arg1 = *(X509 **)&_swig_go_0; 
  
  result = (X509_NAME *)X509_get_subject_name((X509 const *)arg1);
  *(X509_NAME **)&_swig_go_result = (X509_NAME *)result; 
  return _swig_go_result;
}


X509_NAME *_wrap_X509_get_issuer_name_libssl_cc5c18f307e68e7f(X509 *_swig_go_0) {
  X509 *arg1 = (X509 *) 0 ;
  X509_NAME *result = 0 ;
  X509_NAME *_swig_go_result;
  
  arg1 = *(X509 **)&_swig_go_0; 
  
  result = (X509_NAME *)X509_get_issuer_name((X509 const *)arg1);
  *(X509_NAME **)&_swig_go_result = (X509_NAME *)result; 
  return _swig_go_result;
}


_gostring_ _wrap_X509_verify_cert_error_string_libssl_cc5c18f307e68e7f(long long _swig_go_0) {
  long arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (long)_swig_go_0; 
  
  result = (char *)X509_verify_cert_error_string(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_X509_STORE_CTX_get_error_libssl_cc5c18f307e68e7f(X509_STORE_CTX *_swig_go_0) {
  X509_STORE_CTX *arg1 = (X509_STORE_CTX *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(X509_STORE_CTX **)&_swig_go_0; 
  
  result = (int)X509_STORE_CTX_get_error(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


EVP_MD *_wrap_EVP_sha256_libssl_cc5c18f307e68e7f() {
  EVP_MD *result = 0 ;
  EVP_MD *_swig_go_result;
  
  
  result = (EVP_MD *)EVP_sha256();
  *(EVP_MD **)&_swig_go_result = (EVP_MD *)result; 
  return _swig_go_result;
}


EVP_MD *_wrap_EVP_sha512_libssl_cc5c18f307e68e7f() {
  EVP_MD *result = 0 ;
  EVP_MD *_swig_go_result;
  
  
  result = (EVP_MD *)EVP_sha512();
  *(EVP_MD **)&_swig_go_result = (EVP_MD *)result; 
  return _swig_go_result;
}


EVP_MD *_wrap_EVP_sha1_libssl_cc5c18f307e68e7f() {
  EVP_MD *result = 0 ;
  EVP_MD *_swig_go_result;
  
  
  result = (EVP_MD *)EVP_sha1();
  *(EVP_MD **)&_swig_go_result = (EVP_MD *)result; 
  return _swig_go_result;
}


EVP_MD *_wrap_EVP_md5_libssl_cc5c18f307e68e7f() {
  EVP_MD *result = 0 ;
  EVP_MD *_swig_go_result;
  
  
  result = (EVP_MD *)EVP_md5();
  *(EVP_MD **)&_swig_go_result = (EVP_MD *)result; 
  return _swig_go_result;
}


EVP_CIPHER *_wrap_EVP_aes_128_cbc_libssl_cc5c18f307e68e7f() {
  EVP_CIPHER *result = 0 ;
  EVP_CIPHER *_swig_go_result;
  
  
  result = (EVP_CIPHER *)EVP_aes_128_cbc();
  *(EVP_CIPHER **)&_swig_go_result = (EVP_CIPHER *)result; 
  return _swig_go_result;
}


EVP_CIPHER *_wrap_EVP_aes_256_cbc_libssl_cc5c18f307e68e7f() {
  EVP_CIPHER *result = 0 ;
  EVP_CIPHER *_swig_go_result;
  
  
  result = (EVP_CIPHER *)EVP_aes_256_cbc();
  *(EVP_CIPHER **)&_swig_go_result = (EVP_CIPHER *)result; 
  return _swig_go_result;
}


EVP_CIPHER *_wrap_EVP_aes_128_cfb_libssl_cc5c18f307e68e7f() {
  EVP_CIPHER *result = 0 ;
  EVP_CIPHER *_swig_go_result;
  
  
  result = (EVP_CIPHER *)EVP_aes_128_cfb();
  *(EVP_CIPHER **)&_swig_go_result = (EVP_CIPHER *)result; 
  return _swig_go_result;
}


EVP_CIPHER *_wrap_EVP_aes_256_cfb_libssl_cc5c18f307e68e7f() {
  EVP_CIPHER *result = 0 ;
  EVP_CIPHER *_swig_go_result;
  
  
  result = (EVP_CIPHER *)EVP_aes_256_cfb();
  *(EVP_CIPHER **)&_swig_go_result = (EVP_CIPHER *)result; 
  return _swig_go_result;
}


EVP_CIPHER *_wrap_EVP_aes_128_gcm_libssl_cc5c18f307e68e7f() {
  EVP_CIPHER *result = 0 ;
  EVP_CIPHER *_swig_go_result;
  
  
  result = (EVP_CIPHER *)EVP_aes_128_gcm();
  *(EVP_CIPHER **)&_swig_go_result = (EVP_CIPHER *)result; 
  return _swig_go_result;
}


EVP_CIPHER *_wrap_EVP_aes_256_gcm_libssl_cc5c18f307e68e7f() {
  EVP_CIPHER *result = 0 ;
  EVP_CIPHER *_swig_go_result;
  
  
  result = (EVP_CIPHER *)EVP_aes_256_gcm();
  *(EVP_CIPHER **)&_swig_go_result = (EVP_CIPHER *)result; 
  return _swig_go_result;
}


intgo _wrap_EVP_CIPHER_key_length_libssl_cc5c18f307e68e7f(EVP_CIPHER *_swig_go_0) {
  EVP_CIPHER *arg1 = (EVP_CIPHER *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(EVP_CIPHER **)&_swig_go_0; 
  
  result = (int)EVP_CIPHER_key_length((EVP_CIPHER const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_EVP_CIPHER_iv_length_libssl_cc5c18f307e68e7f(EVP_CIPHER *_swig_go_0) {
  EVP_CIPHER *arg1 = (EVP_CIPHER *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(EVP_CIPHER **)&_swig_go_0; 
  
  result = (int)EVP_CIPHER_iv_length((EVP_CIPHER const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

